server:
  port: 8761

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/station?serverTimezone=UTC&useSSL=false&characterEncoding=utf8

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
