server:
  port: 8848

spring:
  devtools:
    restart:
      enabled: true
  application:
    name: service-feign
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/station?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: utf-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/